name: tri_inv
channels:
  - fastai
  - conda-forge
  - pytorch
  - anaconda
  - defaults
dependencies:
  - python=3.9
  - jsonschema
  - jsonargparse
  - torchvision=0.13
  - pytorch=1.12
  - cudatoolkit=11.3
  - opencv
  - timm=0.6.7
  - scikit-learn=1.1.1
  - transformers
  - pandas