name: round11_explore
channels:
  - pytorch
  - defaults
  - conda-forge
  - anaconda
dependencies:
  - python=3.9
  - jsonschema
  - pytorch=1.12
  - torchaudio
  - cudatoolkit=11.3
  - torchvision=0.13
  - opencv
  - transformers
  - scikit-learn=1.1.1
  - jsonargparse
  - pandas